---
- name: ollama
  hosts: all

  # Gather machine informations
  gather_facts: no

  # Enable root previlegies
  become: no

  vars:
    app_name: ollama
    app_image: docker.io/ollama/ollama:0.13.1
    app_internal_port: 11434
    app_external_port: 11434

    app_data_path: "{{ global_app_data_path }}/{{ app_name }}"
    app_timezone: "{{ global_timezone }}"

  # Run suitable scripts
  tasks:
    - name: Create {{ app_name }} data directory
      file:
        path: "{{ app_data_path }}"
        state: directory
        mode: "0755"

    - name: Create {{ app_name }} data directory
      file:
        path: "{{ global_data_path }}/ollama"
        state: directory
        mode: "0755"

    - name: Pull {{ app_name }} image
      containers.podman.podman_image:
        name: "{{ app_image }}"
        state: present

    - name: Create {{ app_name }} container
      containers.podman.podman_container:
        name: "{{ app_name }}"
        image: "{{ app_image }}"
        state: started
        recreate: yes
        memory: 4gb
        network: host
        ports:
          - "{{ app_external_port }}:{{ app_internal_port }}"
        expose:
          - "{{ app_external_port }}"
        volumes:
          - "{{ global_data_path }}/ollama:/root/.ollama"
        env:
          PUID: 1000
          PGID: 1000
          TZ: "{{ app_timezone }}"
          OLLAMA_ORIGINS: http://100.70.35.33

    - name: Systemd unit files for {{ app_name }} container
      containers.podman.podman_generate_systemd:
        name: "{{ app_name }}"
        dest: "~/.config/systemd/user/"
