---
- name: syncthing
  hosts: all

  # Gather machine informations
  gather_facts: yes

  # Enable root previlegies
  become: no

  vars:
    app_name: syncthing
    app_image: lscr.io/linuxserver/syncthing:latest
    app_internal_port: 8384
    app_external_port: 8384

    app_data_path: "{{ global_app_data_path }}/{{ app_name }}"
    app_timezone: "{{ global_timezone }}"

  # Run suitable scripts
  tasks:
    - name: Create {{ app_name }} data directory
      file:
        path: "{{ global_data_path }}"
        state: directory
        mode: "0755"

    #- name: Create {{ app_name }} data directory
    #  file:
    #    path: "{{ global_data_path }}/syncthing"
    #    state: directory
    #    mode: "0755"

    - name: Pull {{ app_name }} image
      containers.podman.podman_image:
        name: "{{ app_image }}"
        state: present

    - name: Create {{ app_name }} container
      containers.podman.podman_container:
        name: "{{ app_name }}"
        image: "{{ app_image }}"
        state: started
        recreate: yes
        memory: 128mb
        ports:
          - "{{ app_external_port }}:{{ app_internal_port }}"
          - 22000:22000/tcp
          - 22000:22000/udp
          - 21027:21027/udp
        expose:
          - "{{ app_external_port }}"
        volumes:
          - "{{ global_data_path }}/syncthing/:/config"
          - "{{ global_data_path }}/:/data1:z"
        env:
          PUID: "{{ ansible_facts['user_uid'] }}"
          PGID: "{{ ansible_facts['user_gid'] }}"
          TZ: "{{ app_timezone }}"
          STGUIADDRESS: "http://0.0.0.0:{{ app_external_port }}"

    - name: Systemd unit files for {{ app_name }} container
      containers.podman.podman_generate_systemd:
        name: "{{ app_name }}"
        dest: "~/.config/systemd/user/"
