---
- name: Jellyfin
  hosts: all

  # Gather machine informations
  gather_facts: no

  # Enable root previlegies
  become: no

  vars:
    app_name: Jellyfin
    app_image: docker.io/jellyfin/jellyfin:10.9.8
    app_internal_port: 8096
    app_external_port: 8096
    timezone: Europe/Paris

  # Run suitable scripts
  tasks:

    - name: Create {{ app_name }} Data Directory
      file:
        path: "{{data_path}}/{{app_name}}"
        state: directory
        mode: '0755'

    - name: Create {{ app_name }} Config Directory
      file:
        path: "{{data_path}}/{{app_name}}/config"
        state: directory
        mode: '0755'

    - name: Create {{ app_name }} TvSeries Directory
      file:
        path: "{{data_path}}/{{app_name}}/shows"
        state: directory
        mode: '0755'

    - name: Create {{ app_name }} Movies Directory
      file:
        path: "{{data_path}}/{{app_name}}/movies"
        state: directory
        mode: '0755'

    - name: Pull {{ app_name }} Image
      containers.podman.podman_image:
        name: "{{ app_image }}"
        state: present

    - name: Create {{app_name}} Container
      containers.podman.podman_container:
        name: "{{ app_name }}"
        image: "{{ app_image }}"
        state: started
        recreate: yes
        ports:
          - "{{app_external_port}}:{{app_internal_port}}"
        expose:
          - "{{ app_external_port }}"
        volumes:
          - "{{data_path}}/{{app_name}}/:/config"
          - "{{data_path}}/{{app_name}}/shows:/data/shows"
          - "{{data_path}}/{{app_name}}/movies:/data/movies"
        env:
          PUID: 1000
          PGID: 1000
          TZ: "Etc/UTC"
        #generate_systemd:
        #  path: "~/.config/systemd/user/"
        #  restart_policy: always
        #  time: 120
        #  names: true
        #  container_prefix: container

