---
- name: Qbittorrent
  hosts: all

  # Gather machine informations
  gather_facts: no

  # Enable root previlegies
  become: no

  vars:
    app_name: Qbittorrent
    app_image: docker.io/linuxserver/qbittorrent:4.6.5
    app_internal_port: 8080
    app_external_port: 9080
    timezone: Europe/Paris
    # for now we might need this in the config:
    # WebUI\HostHeaderValidation=false 

  # Run suitable scripts
  tasks:

    - name: Create {{ app_name }} Data Directory
      file:
        path: "{{ data_path }}/{{ app_name }}"
        state: directory
        mode: '0755'

    - name: Create Download Directory
      file:
        path: "{{ data_path }}/downloads"
        state: directory
        mode: '0755'

    - name: Pull {{ app_name }} Image
      containers.podman.podman_image:
        name: "{{ app_image }}"
        state: present

    - name: Create {{app_name}} Container
      containers.podman.podman_container:
        name: "{{ app_name }}"
        image: "{{ app_image }}"
        state: started
        recreate: yes
        ports:
          - "{{ app_external_port }}:{{ app_internal_port }}"
          - 6881:6881
          - 6881:6881/udp
        expose:
          - "{{ app_external_port }}"
        volumes:
          - "{{ data_path }}/{{ app_name }}/:/config/qBittorrent"
          - "{{ data_path }}/downloads/:/downloads"
        env:
          PUID: 1000
          PGID: 1000
          TZ: "{{ timezone }}"
          WEBUI_PORT: "{{ app_internal_port }}"
          TORRENTING_PORT: 6881
        #generate_systemd:
        #  path: "~/.config/systemd/user/"
        #  restart_policy: always
        #  time: 120
        #  names: true
        #  container_prefix: container

