---
- name: Setup server
  hosts: all

  # Gather machine informations
  gather_facts: no

  # Enable root previlegies
  become: yes

  # Run suitable scripts
  tasks:

    - name: Install Container Manager
      ansible.builtin.package:
        name: 
          - crun # Container runtime
          - podman # Container manager
          - slirp4netns # Allow user-mode networking for unprivileged network namespaces
          - uidmap # Handle user namespace
          - dbus-user-session
          - fuse-overlayfs
          - systemd-container
        state: present

    - name: Create Dedicated User
      ansible.builtin.user:
        name: "{{server_user}}"

    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: "{{ server_user }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"

    # Avoid the user session to close
    - name: Enable linger for {{ server_user }} user
      ansible.builtin.command: "loginctl enable-linger {{ server_user }}"
